### ISSUE TITLE
это оно?

### ISSUE THREAD

**Issue by gurmanalexander** [AidynMakhataev/eloquent-jsonable#1]
это ты вот эту штуку делал?
https://laravel.com/docs/5.6/queries#json-where-clauses

**Comment by AidynMakhataev** [comment]
Да будет точно в таком формате, у Laravel по дефолту только функция JSON_CONTAINS реализована и то там с массивами синтаксис не удобный, а здесь планирую сделать обертку для всех функции с этого [списка](https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html) + еще добавить возможность задавать json схемы и назначать им дефолтные значения.
